version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    allow:
      - dependency-name: "@department-of-veterans-affairs/css-library"
      - dependency-name: "@department-of-veterans-affairs/component-library"
    groups:
      va-design-system-libraries:
        patterns:
          - "@department-of-veterans-affairs/css-library"
          - "@department-of-veterans-affairs/component-library"
