name: 2. 📖 Documentation request form
description: Suggest an update to documentation
labels: ["vsp-design-system-team"]
body:
- type: checkboxes
  attributes:
    label: Duplicate check
    options:
      - label: I've searched for any related issues and avoided creating a duplicate issue.
        required: true
- type: dropdown
  attributes:
    label: "This update is for:"
    options:
      - Content style guide
      - Component
      - Pattern
      - Utility
      - Other
  validations:
    required: true
- type: input
  attributes:
    label: What is the name?
    description: Please describe the name of the component/pattern/utility, or section in the content style guide this update applies to.
  validations:
    required: true
- type: checkboxes
  attributes:
    label: What is the nature of this update?
    description: Please provide all that apply. Not all are required.
    options:
      - label: How to build this component/pattern
      - label: When to use this component/pattern
      - label: When to use something else
      - label: Usability guidance
      - label: Accessibility
      - label: Implementation
      - label: Research insights
      - label: Package information
- type: textarea
  attributes:
    label: What problem does this solve?
    description: Please describe the problem and how this proposed solution solves it.
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional Context
    description: Add any other context or screenshots that might be helpful
