import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * VA Design System Sidebars
 * Matches the IA structure of design.va.gov
 */
const sidebars: SidebarsConfig = {
  // Components
  componentsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'components',
    },
  ],

  // Patterns
  patternsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'patterns',
    },
  ],

  // Templates
  templatesSidebar: [
    {
      type: 'autogenerated',
      dirName: 'templates',
    },
  ],

  // Foundation
  foundationSidebar: [
    {
      type: 'autogenerated',
      dirName: 'foundation',
    },
  ],

  // Content
  contentSidebar: [
    {
      type: 'autogenerated',
      dirName: 'content',
    },
  ],

  // IA (Information Architecture)
  iaSidebar: [
    {
      type: 'autogenerated',
      dirName: 'ia',
    },
  ],

  // Accessibility
  accessibilitySidebar: [
    {
      type: 'autogenerated',
      dirName: 'accessibility',
    },
  ],

  // About
  aboutSidebar: [
    {
      type: 'autogenerated',
      dirName: 'about',
    },
  ],
};

export default sidebars;
