/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "VA.gov Design System",
  "tagline": "Design system, component library, and development guides for VA.gov",
  "favicon": "img/favicon.ico",
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": true,
      "useCssCascadeLayers": true
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "markdown": {
    "mermaid": true,
    "format": "mdx",
    "emoji": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    },
    "hooks": {
      "onBrokenMarkdownLinks": "warn",
      "onBrokenMarkdownImages": "throw"
    }
  },
  "themes": [
    "@docusaurus/theme-mermaid"
  ],
  "plugins": [
    [
      "docusaurus-lunr-search",
      {
        "languages": [
          "en"
        ],
        "indexBaseUrl": true
      }
    ]
  ],
  "url": "https://design.va.gov",
  "baseUrl": "/",
  "organizationName": "department-of-veterans-affairs",
  "projectName": "vads-design-system",
  "onBrokenLinks": "warn",
  "onBrokenAnchors": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "./sidebars.ts",
          "remarkPlugins": [],
          "exclude": [
            "**/_partials/**",
            "**/_template.mdx",
            "**/patterns/_template.mdx"
          ]
        },
        "blog": {
          "showReadingTime": true,
          "blogTitle": "Release Notes",
          "blogDescription": "VA Design System updates and releases",
          "feedOptions": {
            "type": [
              "rss",
              "atom"
            ],
            "xslt": true
          }
        },
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/va-social-card.jpg",
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": true
    },
    "navbar": {
      "title": "VA Design System",
      "logo": {
        "alt": "VA.gov Logo",
        "src": "img/logo.svg"
      },
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "componentsSidebar",
          "position": "left",
          "label": "Components"
        },
        {
          "type": "docSidebar",
          "sidebarId": "patternsSidebar",
          "position": "left",
          "label": "Patterns"
        },
        {
          "type": "docSidebar",
          "sidebarId": "templatesSidebar",
          "position": "left",
          "label": "Templates"
        },
        {
          "type": "docSidebar",
          "sidebarId": "foundationSidebar",
          "position": "left",
          "label": "Foundation"
        },
        {
          "type": "docSidebar",
          "sidebarId": "contentSidebar",
          "position": "left",
          "label": "Content"
        },
        {
          "type": "docSidebar",
          "sidebarId": "iaSidebar",
          "position": "left",
          "label": "IA"
        },
        {
          "type": "docSidebar",
          "sidebarId": "accessibilitySidebar",
          "position": "left",
          "label": "Accessibility"
        },
        {
          "type": "docSidebar",
          "sidebarId": "aboutSidebar",
          "position": "left",
          "label": "About"
        },
        {
          "href": "https://design.va.gov/storybook/",
          "label": "Storybook",
          "position": "right"
        },
        {
          "href": "https://github.com/department-of-veterans-affairs/vets-design-system-documentation",
          "label": "GitHub",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Documentation",
          "items": [
            {
              "label": "Components",
              "to": "/docs/components"
            },
            {
              "label": "Patterns",
              "to": "/docs/patterns"
            },
            {
              "label": "Foundation",
              "to": "/docs/foundation"
            },
            {
              "label": "Content",
              "to": "/docs/content"
            }
          ]
        },
        {
          "title": "Resources",
          "items": [
            {
              "label": "Storybook",
              "href": "https://design.va.gov/storybook/"
            },
            {
              "label": "Figma Library",
              "href": "https://www.figma.com/@vagov"
            },
            {
              "label": "GitHub",
              "href": "https://github.com/department-of-veterans-affairs"
            }
          ]
        },
        {
          "title": "About",
          "items": [
            {
              "label": "Accessibility",
              "to": "/docs/accessibility"
            },
            {
              "label": "About",
              "to": "/docs/about"
            },
            {
              "label": "Release Notes",
              "to": "/blog"
            }
          ]
        }
      ],
      "copyright": "An official website of the United States government."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "bash",
        "json",
        "scss"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    },
    "mermaid": {
      "theme": {
        "dark": "dark",
        "light": "default"
      },
      "options": {}
    }
  },
  "baseUrlIssueBanner": true,
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
