name: Update Whats New Releases

on:
  workflow_dispatch:

jobs:
  release-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # important to get all tags

      - name: Find latest Sprint tag
        id: latest_tag
        run: |
          LATEST_TAG=$(git tag --list "Sprint-*" --sort=-creatordate | head -n 1)
          if [ -z "$LATEST_TAG" ]; then
            echo "No Sprint tag found!"
            exit 1
          fi
          echo "latest_tag=$LATEST_TAG" >> $GITHUB_OUTPUT
          echo "Using tag $LATEST_TAG"

      - name: Install Yarn
        run: npm install -g yarn

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Create release branch from latest Sprint tag
        id: branch
        run: |
          BRANCH="release/${{ steps.latest_tag.outputs.latest_tag }}"
          git checkout -b "$BRANCH" "${{ steps.latest_tag.outputs.latest_tag }}"
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT

      - name: Run update-releases script
        run: rm -rf json_data_cache && yarn run build

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Release updates for ${{ steps.latest_tag.outputs.latest_tag }}" || echo "No changes to commit"

      - name: Push branch
        run: git push origin "${{ steps.branch.outputs.branch }}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.UPDATE_WHATS_NEW }}
          branch: ${{ steps.branch.outputs.branch }}
          title: "Release ${{ steps.latest_tag.outputs.latest_tag }}"
          body: "Automated PR for release ${{ steps.latest_tag.outputs.latest_tag }}"
          base: main
